
<?php extract($state);// Make $state keys available as variables in the layout/view
/*Avoid\n*/?><!DOCTYPE html>
<html lang="en"<?php /*manifest="/<?php echo (!!ShopifYStandard::getInstance()->debug()?'debug':'production').'.php.appcache'; ?>" */ ?>>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo isset($html_title)&&!empty($html_title) ? $html_title : "Home Page"; ?></title>
    <!-- Bootstrap -->
    <link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/stylesheets/app.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <![endif]-->
	<?php echo "<!-- vars: ".implode(", ", array_keys($state))." -->".PHP_EOL; ?>
</head>
<body>
	<div class="app container">
		<header class="page-header row">
			<h1 class="page-title"><?php echo isset($page_title) ? $page_title : $html_title; ?></h1>
			<?php if(isset($page_lead)): ?>
			<p class="lead"><?php echo $page_lead; ?></p>
			<?php endif; ?>
		</header>
		<?php /*////////////////////////////////// Dump for Debugging ////////////////////////////////*/
			if(isset($dumpme)): ?><!-- Dump Dumper Variable -->
			<a href="#dumpme" data-toggle="collapse">Toggle DumpMe</a>
			<pre id="dumpme" class="collapse in" style="white-space: pre;"><?php echo var_export($dumpme, true); ?></pre>
		<?php endif; /*/////////////////////////// Proceed with Layout Page: ////////////////////////*/ 
			if(isset($automation_details)): ?><!-- automation_details collapsables -->
			<a href="#automation_details" data-toggle="collapse">Automation Details</a>
			<pre id="automation_details" class="collapse" style="white-space: pre;"><?php echo var_export($automation_details,true); ?></pre>
		<?php endif; ?>
		<?php loadPartial('alerts/display-alerts', $state); ?>
		<?php /** Include View in Layout (for specific contorller and action, make sure it exists) */
		$view_path = realpath(__DIR__."/../$controller/".(isset($_use_view)?$_use_view:($_use_view=$action)).".phtml");
			include (!$view_path||$_use_view==="404" ? realpath(__DIR__."/../errors/404.phtml") : $view_path);
		/******* End inclusion of view *********************************************************** */ ?>
	</div><?php /** Include Javascripts and Instatiate Below ***********************************/ ?>
    <script type="text/javascript" src="/assets/javascripts/jquery-2.1.4<?php echo $db->debug()?'.js':'.min.js'; ?>"></script>
    <script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/assets/javascripts/lib.js"></script>
	<script type="text/javascript" src="/assets/javascripts/app.js"></script>
	<script type="text/javascript">
	(function(w,d,App) {
		var App = new App({
			"route"  : {
				"controller": "<?php echo $controller; ?>",
				"action"    : "<?php echo $action; ?>",
				"req_etc"	: <?php echo !empty($req_etc) ? json_encode($req_etc) : "{}"; ?>,
				"params"	: <?php echo !empty($params)  ? json_encode($params)  : "{}"; ?>
			},
			"referer": <?php echo '"'.REFERER().'"';
			if(isset($set_url)): ?>,
			"set_url": "<?php echo $set_url; ?>"<?php
			endif;
			if(isset($auto_advance)): ?>,
			"auto_advance": <?php echo boolval($auto_advance) ? "true" : "false"; ?><?php
			endif; ?>
		});
		window.redoAction = function() {
			App.doAction(App.state.route);
		};
	})(window,document,App);
	</script>
</body>
</html>
