<?php
/**
 * Index View For Index Controller
 * Filepath: [Project]/views/index/index.phtml
 **/
// Make $state keys available as variables in the view
// echo "<!-- vars: ".implode(", ", array_keys($state))." -->".PHP_EOL;
// extract($state);
// if(isset($dumpme)): ? >
// <!-- Dump Dumper Variable -->
// <div style="white-space: pre;"><?php echo var_export($dumpme, true); ? ></div>
// <?php endif;
/*/////////////////////////// Proceed with View Page: ////////////////////////*/
?>
<?php
	echo "<footer class='pull-right'><small>Loaded at: " . date(DATE_ATOM) . "<small></footer>";