<?php
/**
 * Index View For Index Controller
 * Filepath: [Project]/views/index/index.phtml
 **/
// Make $view_data keys available as variables in the view
echo "<!-- vars: ".implode(", ", array_keys($view_data))." -->".PHP_EOL;
extract($view_data);
if(isset($dumpme)): ?>
<!-- Dump Dumper Variable -->
<div style="white-space: pre;"><?php echo var_export($dumpme, true); ?></div>
<?php endif;
/*/////////////////////////// Proceed with View Page: ////////////////////////*/
?>